### ISSUE TITLE
Dataset viewer issue: first page is missing elements

### ISSUE THREAD

**Issue by lhoestq** [huggingface/datasets-server#1128] opened 2023-05-03 10:04 UTC
See https://huggingface.co/datasets/gem/viewer/totto/train?p=0

the first page of the viewer shows 10 rows instead of 100. The other pages are correctly showing 100 rows though

**Comment by severo** [comment] 2023-05-03 11:30
Yes, I don't know how we should manage this. It's because /first-rows applies "truncation", in order to always have a small response (< 1MB), while /rows always returns 100 rows, even if the response is very big

**Comment by severo** [comment] 2023-05-03 11:31
One way is to use /rows if available, and /first-rows only as a fallback. But the issue is that /rows can be slow on the first access, while /first-rows is immediate.

**Comment by lhoestq** [comment] 2023-05-03 11:58
Maybe `p=0` should use /rows, and if `p` is not specified it shows the preview ?

**Comment by severo** [comment] 2023-06-02 15:55
See duplicate https://github.com/huggingface/datasets-server/issues/1292. I'm closing this one, since the discussion is more advanced on the other one.

**Closed by severo** 2023-06-02 15:55 UTC
Labels: bug
