### ISSUE TITLE
Dataset Viewer issue for bigscience/P3 of setset 'super_glue_cb_GPT_3_style'

### ISSUE THREAD

**Issue by VoiceBeer** [huggingface/datasets-server#960] opened 2023-03-20 08:34 UTC
### Link

https://huggingface.co/datasets/bigscience/P3

### Description

The dataset viewer is not working for dataset bigscience/P3.

Error details:
The dataset preview of this split is not available.
Job runner crashed while running this job (missing heartbeats).
```
Error code:   JobRunnerCrashedError

```

**Comment by severo** [comment] 2023-03-20 17:10
It seems to be fixed. Is there a specific URL where you see the error?

<img width="1020" alt="Capture d’écran 2023-03-20 à 18 10 29" src="https://user-images.githubusercontent.com/1676121/226416017-a5f22a86-eba0-4222-b867-e7bbe1e52e34.png">

**Comment by VoiceBeer** [comment] 2023-03-21 10:43
Hi @severo ! Sorry for the miss
<img width="1587" alt="image" src="https://user-images.githubusercontent.com/18626699/226582837-85b74936-c902-4bd0-aecb-92b581d7b5cb.png">

BTW, I was wondering why the Story Cloze dataset is not on the list? And how do I download it? Thx

**Comment by severo** [comment] 2023-03-21 10:48
OK, thanks. Putting details for the investigation

https://huggingface.co/datasets/bigscience/P3/viewer/super_glue_cb_GPT_3_style/train

<img width="698" alt="Capture d’écran 2023-03-21 à 11 47 49" src="https://user-images.githubusercontent.com/1676121/226584294-2ff3f17e-53cc-455c-a943-ca0d6a5ccb99.png">

**Comment by albertvillanova** [comment] 2023-03-21 12:33
I am investigating the cause of the crash.

@VoiceBeer in relation with your question the Story Cloze dataset, I think it is better you ask it to the dataset owners/creators in their Community tab: https://huggingface.co/datasets/bigscience/P3/discussions

**Comment by albertvillanova** [comment] 2023-03-21 12:49
I have reviewed and tested the loading script for this configuration and I didn't find any issue. I guess the job crashed because of the large number of configurations.

@severo I think it is not yet possible to rerun the script for just one configuration. Therefore, we should force the rerun for the entire dataset? If you confirm this, I can manually force the update for the entire dataset.

**Comment by severo** [comment] 2023-03-21 12:53
You can force refresh the first rows only for one split with a POST request to the admin endpoint: https://datasets-server.huggingface.co/admin/force-refresh/first-rows?dataset=P3&config=super_glue_cb_GPT_3_style&split=train. Requires to pass your HF token in the authentication header.

**Comment by VoiceBeer** [comment] 2023-03-22 06:11
> I am investigating the cause of the crash.
> 
> @VoiceBeer in relation with your question the Story Cloze dataset, I think it is better you ask it to the dataset owners/creators in their Community tab: https://huggingface.co/datasets/bigscience/P3/discussions

Hi @albertvillanova, thx for your help! Have a good day :D

**Comment by albertvillanova** [comment] 2023-03-24 09:46
The viewer is working now.

I'm closing this issue.

**Closed by albertvillanova** 2023-03-24 09:46 UTC
Labels: bug

**Comment by severo** [comment] 2023-03-24 12:42
Thanks, it works, indeed.

https://huggingface.co/datasets/bigscience/P3/viewer/super_glue_cb_GPT_3_style/train

<img width="1545" alt="Capture d’écran 2023-03-24 à 13 41 11" src="https://user-images.githubusercontent.com/1676121/227524046-fe79b0be-2198-4cad-a4ec-2f5f6555a387.png">
