### ISSUE TITLE
Dataset Viewer issue for THUIR/T2Ranking

### ISSUE THREAD

**Issue by Deriq-Qian-Dong** [huggingface/datasets-server#1030] opened 2023-04-06 16:46 UTC
### Link

https://huggingface.co/datasets/THUIR/T2Ranking

### Description

The dataset viewer is not working for dataset THUIR/T2Ranking.

Error details:

```
Error code:   JobRunnerCrashedError

```

**Comment by albertvillanova** [comment] 2023-04-07 06:34
Thanks for reporting, @Deriq-Qian-Dong.

I complete the information: the `JobRunnerCrashedError` is raised by configurations:
- train.bm25.tsv
- train.bm25.tsv

**Comment by albertvillanova** [comment] 2023-04-07 06:41
Thanks for reporting @Deriq-Qian-Dong.

Can you load the dataset in your machine for any of those configurations?
```python
from datasets import load_dataset

ds = load_dataset("THUIR/T2Ranking", "train.mined.tsv")
```

Please note that the issue is not with the dataset viewer itself, but with your loading script: you are trying to load into RAM memory files with sizes 5.58 GB (`train.mined.tsv`) and 3.65 GB (`train.bm25.tsv`):
```python
data = pd.read_csv(filepath, sep='\t', quoting=3)
```

As the issue is not specifically related to the viewer, I'm transferring it to your dataset "Community" tab: https://huggingface.co/datasets/THUIR/T2Ranking/discussions/1
Let's continue the discussion there.

**Closed by albertvillanova** 2023-04-07 06:41 UTC
Labels: bug
