### ISSUE TITLE
The API returns the wrong row number

### ISSUE THREAD

**Issue by yuanyehome** [huggingface/datasets-server#2581] opened 2024-03-13 04:42 UTC
As stated in this post: https://discuss.huggingface.co/t/got-wrong-row-number-of-dataset-viewer/77132, I got the wrong number on the dataset repo page. The numbers are correct if I download the repo, but when I follow the instructions in https://huggingface.co/docs/datasets-server/size?code=curl, the numbers of rows in the response are also wrong. I'd like to know if there is something wrong with my usage or if there are some bugs in the API.

**Comment by yuanyehome** [comment] 2024-03-13 06:05
Update:
When I called
```bash
curl https://datasets-server.huggingface.co/statistics\?dataset\=${dataset_path}\&config\=default\&split\=test \                                                                    ─╯
        -X GET \
        -H "Authorization: Bearer ${API_TOKEN}"
```
I will get the correct `number_examples`.

But when I called
```bash
curl https://datasets-server.huggingface.co/size\?dataset\=${dataset_path} \                                                                                                        ─╯
        -X GET \
        -H "Authorization: Bearer ${API_TOKEN}"
```
The `num_rows` attribute gives the wrong number.

**Comment by yuanyehome** [comment] 2024-03-13 09:06
Update:
I've checked the API source code and recent commit, and it seems that this function has be changed yesterday: https://github.com/huggingface/datasets-server/blob/476c564b218c98eb9005ecd73c81d62d2d2f2563/services/worker/src/worker/job_runners/config/parquet_and_info.py#L666-L737.

The `num_examples` is miscalculated. I think that #L684 should be in the for-loop.

**Comment by severo** [comment] 2024-03-13 09:47
wow, well spotted, thanks!

**Comment by severo** [comment] 2024-03-13 09:53
Reports:
- https://discuss.huggingface.co/t/got-wrong-row-number-of-dataset-viewer/77132/3
- https://discord.com/channels/879548962464493619/1217113204912816148/1217113204912816148

**Comment by severo** [comment] 2024-03-13 09:59
related to https://github.com/huggingface/datasets-server/pull/2564

**Comment by severo** [comment] 2024-03-13 10:23
Should be fixed by https://github.com/huggingface/datasets-server/pull/2582

**Closed** 2024-03-13 10:42 UTC
Labels: bug, P0

**Comment by severo** [comment] 2024-03-13 10:57
Fixed on https://huggingface.co/datasets/ab24g21/14to18

<img width="612" alt="Capture d’écran 2024-03-13 à 11 56 32" src="https://github.com/huggingface/datasets-server/assets/1676121/6e25e483-c8ec-448a-a1d9-128bc0cf3514">
<img width="542" alt="Capture d’écran 2024-03-13 à 11 56 53" src="https://github.com/huggingface/datasets-server/assets/1676121/3fc34d81-b384-4db3-bd0d-87b084a1d2fa">

**Comment by severo** [comment] 2024-03-13 10:58
thanks a lot @yuanyehome for the report and for finding the root cause
